
class Component extends DCLogic {
  state = { view: "intro", fi: 0, step: 0, wfi: 0, menuOpen: false, sysKey: "tms" };
  stepNames = /*@fp-content:step-names*/null;

  placeholders = /*@fp-content:placeholders*/null;

  // Standard shipping workflows — cards + animated diagram slugs
  // (diagrams generated by tools/build-workflows.js into modules/workflows/)
  workflows = /*@fp-content:workflows*/null;

  // WMS + OMS capability libraries (grounded in the FreightPOP Knowledge Center)
  sysData = /*@fp-content:sys-data*/null;

  features = /*@fp-content:features-tms*/null;


  // WMS + OMS module flows — grounded in the capability library above.
  // Quotes are illustrative personas (not attributed customers); ROI stats describe product behavior, not performance claims.
  wmsFeatures = /*@fp-content:features-wms*/null;

  omsFeatures = /*@fp-content:features-oms*/null;

  // NetSuite demo track — workflows FreightPOP supports on NetSuite (SuiteApp +
  // bilateral integration), grounded in the ERP Integration Docs / Update Briefs.
  nsFeatures = /*@fp-content:features-netsuite*/null;

  featureSets = { tms: this.features, wms: this.wmsFeatures, oms: this.omsFeatures, netsuite: this.nsFeatures };

  setRoot = (el) => { this.root = el; };
  setHeroWrap = (el) => { this.heroWrap = el; };
  setHeroFrame = (el) => { this.heroFrame = el; };

  componentDidMount() {
    this._onKey = (e) => {
      if (this.state.menuOpen && e.key === "Escape") { this.setState({ menuOpen: false }); return; }
      if (this.state.view === "intro" && (e.key === "ArrowRight" || e.key === "PageDown")) { e.preventDefault(); this.goExplore(); return; }
      if (this.state.view === "explore") {
        if (e.key === "ArrowRight" || e.key === "PageDown") { e.preventDefault(); this.goMainMenu(); }
        else if (e.key === "Escape" || e.key === "ArrowLeft") this.goIntro();
        return;
      }
      if (this.state.view === "mainmenu") {
        if (e.key === "ArrowRight" || e.key === "PageDown") { e.preventDefault(); this.goHub(); }
        else if (e.key === "Escape" || e.key === "ArrowLeft") this.goExplore();
        return;
      }
      if (this.state.view === "wms" || this.state.view === "oms" || this.state.view === "netsuite" || this.state.view === "erp" || this.state.view === "carriers" || this.state.view === "workflows") {
        if (e.key === "Escape" || e.key === "ArrowLeft") this.goMainMenu();
        return;
      }
      if (this.state.view === "workflow") {
        if (e.key === "ArrowRight" || e.key === "PageDown") { e.preventDefault(); this.wfNext(); }
        else if (e.key === "ArrowLeft" || e.key === "PageUp") { e.preventDefault(); this.wfPrev(); }
        else if (e.key === "Escape") this.goWorkflows();
        return;
      }
      if (this.state.view !== "feature") return;
      if (e.key === "ArrowRight" || e.key === "PageDown") { e.preventDefault(); this.featNext(); }
      else if (e.key === "ArrowLeft" || e.key === "PageUp") { e.preventDefault(); this.featPrev(); }
      else if (e.key === "Escape") this.goHub();
    };
    window.addEventListener("keydown", this._onKey);
  }

  componentWillUnmount() {
    if (this._onKey) window.removeEventListener("keydown", this._onKey);
    if (this.ro) this.ro.disconnect();
    if (this._onResize) window.removeEventListener("resize", this._onResize);
    if (this._riveT) clearTimeout(this._riveT);
    try { if (this.riveInst && this.riveInst.cleanup) this.riveInst.cleanup(); } catch (e) {}
  }

  revealActive() {
    if (!this.root) return;
    this.root.querySelectorAll("[data-reveal]").forEach((el) => {
      if (el.offsetParent === null) return;
      el.style.animation = "none"; void el.offsetWidth;
      el.style.animation = "fpReveal .7s cubic-bezier(.22,.7,.25,1) both";
    });
  }

  // navigation
  goIntro = () => this.setState({ view: "intro", menuOpen: false });
  goExplore = () => this.setState({ view: "explore", menuOpen: false });
  goMainMenu = () => this.setState({ view: "mainmenu", menuOpen: false });
  goHub = () => { const k = this.state.sysKey; if (k === "wms" || k === "oms" || k === "netsuite") this.setState({ view: k, menuOpen: false }); else this.setState({ view: "hub", menuOpen: false }); };
  goTms = () => this.setState({ view: "hub", sysKey: "tms", menuOpen: false });
  goPlaceholder = (k) => this.setState({ view: k, menuOpen: false });
  goWms = () => this.setState({ view: "wms", sysKey: "wms", menuOpen: false });
  goOms = () => this.setState({ view: "oms", sysKey: "oms", menuOpen: false });
  goNetsuite = () => this.setState({ view: "netsuite", sysKey: "netsuite", menuOpen: false });
  curFeats = () => this.featureSets[this.state.sysKey] || this.features;
  goErp = () => this.goPlaceholder("erp");
  goCarriers = () => this.setState({ view: "carriers", menuOpen: false });
  // Standard shipping workflows: grid → animated diagram detail
  goWorkflows = () => this.setState({ view: "workflows", menuOpen: false });
  openWorkflow = (i) => this.setState({ view: "workflow", wfi: i, menuOpen: false });
  wfNext = () => { const n = this.workflows.items.length; if (this.state.wfi < n - 1) this.setState({ wfi: this.state.wfi + 1 }); else this.goWorkflows(); };
  wfPrev = () => { if (this.state.wfi > 0) this.setState({ wfi: this.state.wfi - 1 }); else this.goWorkflows(); };
  goBack = () => {
    const v = this.state.view;
    if (v === "explore") return this.goIntro();
    if (v === "mainmenu") return this.goExplore();
    if (v === "hub") return this.goMainMenu();
    if (v === "feature") return this.goHub();
    if (v === "workflow") return this.goWorkflows();
    return this.goMainMenu();
  };
  openFeature = (i, step, sysKey) => this.setState({ view: "feature", fi: i, step: step || 0, sysKey: sysKey || this.state.sysKey, menuOpen: false });
  toggleMenu = () => this.setState((s) => ({ menuOpen: !s.menuOpen }));
  setStep = (i) => this.setState({ step: i });
  featNext = () => {
    const { step, fi } = this.state;
    if (step < 3) this.setState({ step: step + 1 });
    else if (fi < this.curFeats().length - 1) this.setState({ fi: fi + 1, step: 0 });
    else this.goHub();
  };
  featPrev = () => {
    const { step } = this.state;
    if (step > 0) this.setState({ step: step - 1 });
    else this.goHub();
  };

  // Rive hero
  initHero() {
    this.fitHero();
    if (window.ResizeObserver && this.heroWrap) {
      this.ro = new ResizeObserver(() => this.fitHero());
      this.ro.observe(this.heroWrap);
    }
    this._onResize = () => { this.fitHero(); if (this.state.view === "intro") { try { this.riveInst && this.riveInst.resizeDrawingSurfaceToCanvas && this.riveInst.resizeDrawingSurfaceToCanvas(); } catch (e) {} } };
    window.addEventListener("resize", this._onResize);
    this.startRive();
  }
  fitHero() {
    const w = this.heroWrap, f = this.heroFrame;
    if (!w || !f) return;
    const cw = w.clientWidth, ch = w.clientHeight;
    if (cw < 2 || ch < 2) return;
    const s = Math.min(cw / 1920, ch / 1080);
    f.style.transform = "translate(-50%,-50%) scale(" + (s > 0 ? s : 1) + ")";
  }
  startRive() {
    const frame = this.heroFrame;
    const canvas = frame && frame.querySelector("canvas[data-fp-hero-canvas]");
    if (!canvas) { this._riveT = setTimeout(() => this.startRive(), 120); return; }
    if (!(window.rive && window.rive.Rive)) { this._riveT = setTimeout(() => this.startRive(), 120); return; }
    if (canvas.__fpInit) return;
    canvas.__fpInit = true;
    const runtime = window.rive;
    try { if (runtime.RuntimeLoader && runtime.RuntimeLoader.setWasmUrl) runtime.RuntimeLoader.setWasmUrl((window.__resources && window.__resources.riveWasm) || "assets/rive.wasm"); } catch (e) {}
    try {
      this.riveInst = new runtime.Rive({
        src: (window.__resources && window.__resources.riveHero) || "assets/fp_hero-background.riv",
        canvas: canvas,
        artboard: "Main",
        stateMachines: "State Machine 1",
        autoplay: true,
        autoBind: true,
        layout: new runtime.Layout({ fit: runtime.Fit.Layout || runtime.Fit.Cover, alignment: runtime.Alignment.Center }),
        onLoad: () => { try { this.riveInst.resizeDrawingSurfaceToCanvas(); this.riveInst.play(); } catch (e) {} },
      });
    } catch (e) {}
  }

  renderVals() {
    const { view, fi, step, menuOpen } = this.state;
    const startUrl = this.props.startUrl || "https://willowy-chimera-d486b0.netlify.app/";
    const showMarquee = this.props.showMarquee !== false;
    const feats = this.curFeats();
    const feat = feats[fi] || feats[0];
    const isPlaceholder = view === "erp";
    const isSysHub = view === "wms" || view === "oms" || view === "netsuite";
    const sys = this.sysData[view] || { abbr: "", name: "", kicker: "", intro: "", cards: [] };
    const ph = this.placeholders[view] || { abbr: "", name: "", tag: "" };

    const introStyle = "position:absolute;inset:0;z-index:10;background:#051729;" + (view === "intro" ? "display:block;" : "display:none;");

    // hub cards
    const cards = this.features.map((f, i) => ({
      num: f.num, t1: f.t1, t2: f.t2, tag: f.tag,
      onClick: () => this.openFeature(i, 0, "tms"),
    }));

    // overview menu
    const topRow = "background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.12);border-radius:12px;padding:22px 24px;cursor:pointer;transition:all .2s ease;";
    const topRowActive = "background:rgba(61,214,181,.1);border:1.5px solid #3DD6B5;border-radius:12px;padding:22px 24px;cursor:pointer;box-shadow:0 0 26px rgba(61,214,181,.16);";
    const topMenu = [
      { label: "Intro", sub: "Full-screen overview", onClick: this.goIntro, style: view === "intro" ? topRowActive : topRow },
      { label: "Interactive Walkthrough", sub: "Live product experience", onClick: this.goExplore, style: view === "explore" ? topRowActive : topRow },
      { label: "Main Menu", sub: "Platform · 4 systems", onClick: this.goMainMenu, style: view === "mainmenu" ? topRowActive : topRow },
      { label: "Transportation Management", sub: "Module hub · 9 capabilities", onClick: this.goTms, style: (view === "hub" || (view === "feature" && this.state.sysKey === "tms")) ? topRowActive : topRow },
      { label: "Carrier Integrations", sub: "Every mode · one network", onClick: this.goCarriers, style: view === "carriers" ? topRowActive : topRow },
      { label: "Standard Shipping Workflows", sub: "7 animated flows", onClick: this.goWorkflows, style: (view === "workflows" || view === "workflow") ? topRowActive : topRow },
      { label: "ERP & System Integrations", sub: "54 connected systems", onClick: this.goErp, style: view === "erp" ? topRowActive : topRow },
      { label: "NetSuite Demo Track", sub: "SuiteApp · 6 workflows", onClick: this.goNetsuite, style: (view === "netsuite" || (view === "feature" && this.state.sysKey === "netsuite")) ? topRowActive : topRow },
    ];
    const fCard = "background:rgba(255,255,255,.03);border:1px solid rgba(255,255,255,.10);border-radius:12px;padding:16px 18px;cursor:pointer;transition:all .2s ease;";
    const fCardActive = "background:rgba(61,214,181,.1);border:1.5px solid #3DD6B5;border-radius:12px;padding:16px 18px;cursor:pointer;box-shadow:0 0 22px rgba(61,214,181,.14);";
    const featMenu = this.features.map((f, i) => ({
      num: f.num, label: f.name,
      onClick: () => this.openFeature(i, 0, "tms"),
      style: (view === "feature" && this.state.sysKey === "tms" && i === fi) ? fCardActive : fCard,
    }));
    const wmsMenu = this.featureSets.wms.map((f, i) => ({
      num: f.num, label: f.name,
      onClick: () => this.openFeature(i, 0, "wms"),
      style: (view === "feature" && this.state.sysKey === "wms" && i === fi) ? fCardActive : fCard,
    }));
    const omsMenu = this.featureSets.oms.map((f, i) => ({
      num: f.num, label: f.name,
      onClick: () => this.openFeature(i, 0, "oms"),
      style: (view === "feature" && this.state.sysKey === "oms" && i === fi) ? fCardActive : fCard,
    }));
    const nsMenu = this.featureSets.netsuite.map((f, i) => ({
      num: f.num, label: f.name,
      onClick: () => this.openFeature(i, 0, "netsuite"),
      style: (view === "feature" && this.state.sysKey === "netsuite" && i === fi) ? fCardActive : fCard,
    }));

    const wf = this.workflows.items[this.state.wfi] || this.workflows.items[0];
    const navKey = view + ":" + fi + ":" + step + ":" + this.state.wfi;
    if (this._navKey !== navKey) {
      this._navKey = navKey;
      requestAnimationFrame(() => {
        this.revealActive();
        if (view === "intro") { this.fitHero(); try { if (this.riveInst) { this.riveInst.resizeDrawingSurfaceToCanvas(); this.riveInst.play(); } } catch (e) {} } else { try { this.riveInst && this.riveInst.pause(); } catch (e) {} }
      });
    }

    let crumb0 = "Main Menu", crumb0Click = this.goMainMenu;
    let crumb1 = "", crumb1Click = this.goHub, hasCrumb1 = false;
    let crumbLeaf = "", hasLeaf = false;
    if (view === "explore") { crumb0 = "Interactive Walkthrough"; crumb0Click = this.goExplore; }
    else if (view === "hub") { crumbLeaf = "Transportation Management"; hasLeaf = true; }
    else if (view === "feature") { crumb1 = ({ tms: "Transportation Management", wms: "Warehouse Management", oms: "Order Management", netsuite: "NetSuite Demo Track" })[this.state.sysKey] || "Modules"; crumb1Click = this.goHub; hasCrumb1 = true; crumbLeaf = feat.name; hasLeaf = true; }
    else if (isSysHub) { crumbLeaf = sys.name; hasLeaf = true; }
    else if (isPlaceholder) { crumbLeaf = ph.name; hasLeaf = true; }
    else if (view === "carriers") { crumbLeaf = "Carrier Integrations"; hasLeaf = true; }
    else if (view === "workflows") { crumbLeaf = "Standard Shipping Workflows"; hasLeaf = true; }
    else if (view === "workflow") { crumb1 = "Standard Shipping Workflows"; crumb1Click = this.goWorkflows; hasCrumb1 = true; crumbLeaf = wf.name; hasLeaf = true; }

    return {
      setRoot: this.setRoot, setHeroWrap: this.setHeroWrap, setHeroFrame: this.setHeroFrame,
      introStyle, startUrl, showMarquee,
      isHub: view === "hub", isFeature: view === "feature", isIntro: view === "intro", isExplore: view === "explore", isMainMenu: view === "mainmenu", isPlaceholder, isSysHub, isCarriers: view === "carriers", notIntro: view !== "intro",
      isWorkflows: view === "workflows", isWorkflow: view === "workflow",
      sysAbbr: sys.abbr, sysName: sys.name, sysKicker: sys.kicker, sysIntro: sys.intro, sysCards: sys.cards.map((c, i) => ({ ...c, onClick: () => this.openFeature(i, 0, view) })),
      goExplore: this.goExplore, goStart: this.goExplore,
      goMainMenu: this.goMainMenu, goTms: this.goTms, goWms: this.goWms, goOms: this.goOms, goErp: this.goErp, goNetsuite: this.goNetsuite, goBack: this.goBack,
      goWorkflows: this.goWorkflows, wfNext: this.wfNext, wfPrev: this.wfPrev,
      wfAbbr: this.workflows.abbr, wfSection: this.workflows.name, wfKicker: this.workflows.kicker, wfIntro: this.workflows.intro,
      wfCards: this.workflows.items.map((c, i) => ({ ...c, onClick: () => this.openWorkflow(i) })),
      wfSrc: "../modules/workflows/" + wf.slug + ".html?embed=1", wfName: wf.name,
      wfCounter: "0" + (this.state.wfi + 1) + " / 0" + this.workflows.items.length,
      phAbbr: ph.abbr, phName: ph.name, phTag: ph.tag,
      crumb0, crumb0Click, crumb1, crumb1Click, hasCrumb1, crumbLeaf, hasLeaf,
      featBg: (fi % 2 === 0) ? "#051729" : "#0A2540",
      feat,
      isProblem: step === 0, isBenefit: step === 1, isDemo: step === 2, isRoi: step === 3,
      // Modular live-demo embeds: a module's demo.embed URL (in content JSON)
      // replaces the placeholder panel with a live iframe.
      hasDemoEmbed: !!(feat.demo && feat.demo.embed),
      noDemoEmbed: !(feat.demo && feat.demo.embed),
      demoEmbedSrc: (feat.demo && feat.demo.embed) || 'about:blank',
      goStep0: () => this.setStep(0), goStep1: () => this.setStep(1), goStep2: () => this.setStep(2), goStep3: () => this.setStep(3),
      stepCounter: "0" + (step + 1) + " / 04",
      nextLabel: fi < feats.length - 1 ? "Next module" : "Back to modules",
      modTotal: (feats.length < 10 ? "0" : "") + feats.length,
      cards, topMenu, featMenu, wmsMenu, omsMenu, nsMenu,
      goIntro: this.goIntro, goHub: this.goHub, toggleMenu: this.toggleMenu,
      featNext: this.featNext, featPrev: this.featPrev,
      menuOpen,
    };
  }
}
